backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets/blog" 
public_folder: "/assets/blog" 
collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      -  { label: "Description", name: "description", widget: "string" }
      - {label: "Body", name: "body", widget: "markdown"}